# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 570)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtUsername = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtUsername.setFont(font)
        self.txtUsername.setObjectName("txtUsername")
        self.verticalLayout.addWidget(self.txtUsername)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtPassword = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.horizontalLayout.addWidget(self.txtPassword)
        self.btnTogglePassword = QtWidgets.QPushButton(self.centralwidget)
        self.btnTogglePassword.setObjectName("btnTogglePassword")
        self.horizontalLayout.addWidget(self.btnTogglePassword)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout.addWidget(self.btnLogin)
        self.btnGoRegister = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnGoRegister.setFont(font)
        self.btnGoRegister.setObjectName("btnGoRegister")
        self.verticalLayout.addWidget(self.btnGoRegister)
        self.lblError = QtWidgets.QLabel(self.centralwidget)
        self.lblError.setStyleSheet("color: red;")
        self.lblError.setText("")
        self.lblError.setObjectName("lblError")
        self.verticalLayout.addWidget(self.lblError)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Đăng nhập"))
        self.txtUsername.setPlaceholderText(_translate("MainWindow", "Nhập username"))
        self.txtPassword.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.btnTogglePassword.setText(_translate("MainWindow", "👁"))
        self.btnLogin.setText(_translate("MainWindow", "Đăng nhập"))
        self.btnGoRegister.setText(_translate("MainWindow", "Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
