# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtUsername = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtUsername.setFont(font)
        self.txtUsername.setObjectName("txtUsername")
        self.verticalLayout.addWidget(self.txtUsername)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.txtPassword = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.hboxlayout.addWidget(self.txtPassword)
        self.btnTogglePassword = QtWidgets.QPushButton(self.centralwidget)
        self.btnTogglePassword.setObjectName("btnTogglePassword")
        self.hboxlayout.addWidget(self.btnTogglePassword)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.txtConfirmPassword = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtConfirmPassword.setFont(font)
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.hboxlayout1.addWidget(self.txtConfirmPassword)
        self.btnToggleConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.btnToggleConfirm.setObjectName("btnToggleConfirm")
        self.hboxlayout1.addWidget(self.btnToggleConfirm)
        self.verticalLayout.addLayout(self.hboxlayout1)
        self.btnRegister = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName("btnRegister")
        self.verticalLayout.addWidget(self.btnRegister)
        self.btnBackLogin = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnBackLogin.setFont(font)
        self.btnBackLogin.setObjectName("btnBackLogin")
        self.verticalLayout.addWidget(self.btnBackLogin)
        self.lblError = QtWidgets.QLabel(self.centralwidget)
        self.lblError.setStyleSheet("color: red;")
        self.lblError.setText("")
        self.lblError.setObjectName("lblError")
        self.verticalLayout.addWidget(self.lblError)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register"))
        self.label.setText(_translate("MainWindow", "Đăng ký"))
        self.txtUsername.setPlaceholderText(_translate("MainWindow", "Nhập username"))
        self.txtPassword.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.btnTogglePassword.setText(_translate("MainWindow", "👁"))
        self.txtConfirmPassword.setPlaceholderText(_translate("MainWindow", "Nhập lại mật khẩu"))
        self.btnToggleConfirm.setText(_translate("MainWindow", "👁"))
        self.btnRegister.setText(_translate("MainWindow", "Đăng ký"))
        self.btnBackLogin.setText(_translate("MainWindow", "Quay lại đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
