# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Thongkesuckhoe.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1087, 703)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 471, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(20, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 110, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(20, 170, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_BMI = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_BMI.setGeometry(QtCore.QRect(200, 60, 231, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_BMI.sizePolicy().hasHeightForWidth())
        self.lineEdit_BMI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_BMI.setFont(font)
        self.lineEdit_BMI.setReadOnly(True)
        self.lineEdit_BMI.setObjectName("lineEdit_BMI")
        self.lineEdit_TDEE = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_TDEE.setGeometry(QtCore.QRect(200, 120, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_TDEE.setFont(font)
        self.lineEdit_TDEE.setReadOnly(True)
        self.lineEdit_TDEE.setObjectName("lineEdit_TDEE")
        self.lineEdit_Luongnuoc = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Luongnuoc.setGeometry(QtCore.QRect(200, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Luongnuoc.setFont(font)
        self.lineEdit_Luongnuoc.setReadOnly(True)
        self.lineEdit_Luongnuoc.setObjectName("lineEdit_Luongnuoc")
        self.chart_widget_cannang = QtWidgets.QWidget(Dialog)
        self.chart_widget_cannang.setGeometry(QtCore.QRect(500, 30, 551, 311))
        self.chart_widget_cannang.setObjectName("chart_widget_cannang")
        self.chart_widget_calo = QtWidgets.QWidget(Dialog)
        self.chart_widget_calo.setGeometry(QtCore.QRect(10, 350, 581, 301))
        self.chart_widget_calo.setObjectName("chart_widget_calo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Thống kê sức khỏe "))
        self.label_13.setText(_translate("Dialog", "BMI hiện tại: "))
        self.label_15.setText(_translate("Dialog", "TDEE khuyến nghị:"))
        self.label_16.setText(_translate("Dialog", "Lượng nước cần uống:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
